### ISSUE TITLE
pip install fails on macOS Mojave

### ISSUE THREAD

**Issue by grandynguyen** [codypiersall/pynng#45]
All good just needed cmake. Misread warning as error.

```
Collecting pynng
  Downloading https://files.pythonhosted.org/packages/1b/fb/23266f32a8dfa1c86991b6315577e95b803061de154725a82e5ff6f800d4/pynng-0.4.0.tar.gz (607kB)
    100% |████████████████████████████████| 614kB 805kB/s 
Collecting cffi (from pynng)
  Using cached https://files.pythonhosted.org/packages/f0/48/5aa4ea664eba26dd5142558d04762f5065c02220b4665b3f7eecb9bb614e/cffi-1.12.3-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting sniffio (from pynng)
  Downloading https://files.pythonhosted.org/packages/b3/82/4bd4b7d9c0d1dc0fbfbc2a1e00138e7f3ab85bc239358fe9b78aa2ab586d/sniffio-1.1.0-py3-none-any.whl
Collecting pycparser (from cffi->pynng)
Installing collected packages: pycparser, cffi, sniffio, pynng
  Running setup.py install for pynng ... error
    Complete output from command /Users/gnguyen/Projects/microservices/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-record-2sbmtzsy/install-record.txt --single-version-externally-managed --compile --install-headers /Users/gnguyen/Projects/microservices/.venv/include/site/python3.7/pynng:
    /usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    /private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/build_nng.sh: line 24: cmake: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/setup.py", line 142, in <module>
        test_suite='tests',
      File "/Users/gnguyen/Projects/microservices/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/gnguyen/Projects/microservices/.venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/setup.py", line 88, in run
        build_nng_lib()
      File "/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/setup.py", line 80, in build_nng_lib
        subprocess.check_call(cmd, shell=needs_shell)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 341, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/bin/bash', '/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/build_nng.sh', 'd3bd35ab49ad74528fd9e34cce9016d74dd91943']' returned non-zero exit status 127.
```

**Comment by grandynguyen** [comment]
Opps, looks like upgrading pip and setuptools did do something. The error I was getting before was...

```Collecting pynng
  Downloading https://files.pythonhosted.org/packages/1b/fb/23266f32a8dfa1c86991b6315577e95b803061de154725a82e5ff6f800d4/pynng-0.4.0.tar.gz (607kB)
    100% |████████████████████████████████| 614kB 805kB/s 
Collecting cffi (from pynng)
  Using cached https://files.pythonhosted.org/packages/f0/48/5aa4ea664eba26dd5142558d04762f5065c02220b4665b3f7eecb9bb614e/cffi-1.12.3-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting sniffio (from pynng)
  Downloading https://files.pythonhosted.org/packages/b3/82/4bd4b7d9c0d1dc0fbfbc2a1e00138e7f3ab85bc239358fe9b78aa2ab586d/sniffio-1.1.0-py3-none-any.whl
Collecting pycparser (from cffi->pynng)
Installing collected packages: pycparser, cffi, sniffio, pynng
  Running setup.py install for pynng ... error
    Complete output from command /Users/gnguyen/Projects/microservices/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-record-2sbmtzsy/install-record.txt --single-version-externally-managed --compile --install-headers /Users/gnguyen/Projects/microservices/.venv/include/site/python3.7/pynng:
    /usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    /private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/build_nng.sh: line 24: cmake: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/setup.py", line 142, in <module>
        test_suite='tests',
      File "/Users/gnguyen/Projects/microservices/.venv/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/gnguyen/Projects/microservices/.venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/setup.py", line 88, in run
        build_nng_lib()
      File "/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/setup.py", line 80, in build_nng_lib
        subprocess.check_call(cmd, shell=needs_shell)
      File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 341, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/bin/bash', '/private/var/folders/f0/yk2mvwk92rx0wj1xygs3sjcw000528/T/pip-install-7voii7jk/pynng/build_nng.sh', 'd3bd35ab49ad74528fd9e34cce9016d74dd91943']' returned non-zero exit status 127.
```
