### ISSUE TITLE
s1.send(b'') causes pynng.exceptions.NoMemory: Out of memory

### ISSUE THREAD

**Issue by zhoujin7** [codypiersall/pynng#57]
```python
from pynng import Pair0

with Pair0(listen='tcp://127.0.0.1:54321') as s1, \
        Pair0(dial='tcp://127.0.0.1:54321') as s2:
    s1.send(b'')
    print(s2.recv())
```
```txt
Traceback (most recent call last):
  File "C:/development/pythondev/test/demo.py", line 6, in <module>
    print(s2.recv())
  File "C:\development\pythondev\test\venv\lib\site-packages\pynng\nng.py", line 451, in recv
    check_err(ret)
  File "C:\development\pythondev\test\venv\lib\site-packages\pynng\exceptions.py", line 201, in check_err
    raise exc(string, err)
pynng.exceptions.NoMemory: Out of memory
```

**Comment by codypiersall** [comment]
Thanks for opening this issue, @zhoujin7.  That is a very surprising exception!  I have confirmed that the same behavior is present in upstream nng:

```c
#include <assert.h>
#include <stdio.h>
#include <nng/nng.h>
#include <nng/protocol/pair0/pair.h>

#define CHECK(x) (assert((x) == 0))
#define ADDR "tcp://127.0.0.1:14224"

int main(int argc, char *argv[]) {
    nng_socket s0, s1;
    char *data = NULL;
    size_t *recv_size = NULL;

    CHECK(nng_pair0_open(&s0));
    CHECK(nng_listen(s0, ADDR, NULL, 0));

    CHECK(nng_pair_open(&s1));
    CHECK(nng_dial(s1, ADDR, NULL, 0));

    CHECK(nng_send(s0, "", 0, 0));
    int ret = nng_recv(s1, &data, recv_size, NNG_FLAG_ALLOC);
    assert(ret == NNG_ENOMEM);
    fprintf(stdout, "ret %d\n", ret);

    CHECK(nng_close(s1));
    CHECK(nng_close(s0));
}

```

If you're comfortable with C and the upstream nng library, please create an issue there.  Otherwise, let me know and I will create an issue in nng.

**Comment by codypiersall** [comment]
@zhoujin7 no problem.  I'll post an issue on nng.

**Comment by codypiersall** [comment]
nng [fixed this upstream](https://github.com/nanomsg/nng/commit/6a59b15fba1085432c4c18952680e14d80dd134a) and it's now in v0.6.0.
